# Generated by Django 3.0.8 on 2020-07-07 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='user_LoginId',
            field=models.ForeignKey(db_column='user_LoginId', on_delete=django.db.models.deletion.CASCADE,
                                    to='login.Loginmaster'),
        ),
    ]
