# Generated by Django 3.0.8 on 2020-07-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200706_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='userProfilePhoto',
            field=models.ImageField(default='', upload_to='login/images'),
        ),
    ]
