# Generated by Django 3.0.8 on 2020-07-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200708_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='userProfilePhoto',
            field=models.FileField(upload_to=''),
        ),
    ]
