# Generated by Django 3.0.8 on 2020-07-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200708_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='userProfilePhoto',
            field=models.FileField(default='apple-touch-icon.png', upload_to=''),
        ),
    ]
