# Generated by Django 3.0.8 on 2020-07-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200709_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='userProfilePhoto',
            field=models.FileField(blank=True, default='apple-touch-icon.png', null=True, upload_to=''),
        ),
    ]
