# Generated by Django 3.0.8 on 2020-07-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('login', '0002_auto_20200706_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequestmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(blank=True, max_length=1000)),
                ('msg_From', models.ForeignKey(db_column='msg_From', on_delete=django.db.models.deletion.CASCADE,
                                               related_name='msg_From', to='login.Loginmaster')),
                ('msg_To', models.ForeignKey(db_column='msg_To', on_delete=django.db.models.deletion.CASCADE,
                                             related_name='msg_To', to='login.Loginmaster')),
            ],
        ),
    ]
