# Generated by Django 3.0.8 on 2020-07-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0002_auto_20200707_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgmaster',
            name='msgSendTime',
            field=models.TimeField(null=True),
        ),
    ]
