# Generated by Django 3.0.8 on 2020-07-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0003_msgmaster_msgsendtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgmaster',
            name='msgSendDate',
            field=models.DateField(null=True),
        ),
    ]
