# Generated by Django 3.0.8 on 2020-07-06 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequestmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendRequest_To', models.IntegerField(null=True)),
                ('friendRequest_MSG', models.CharField(blank=True, max_length=1000)),
                ('friendRequest_Action', models.CharField(max_length=50)),
                ('friendRequest_From',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Loginmaster')),
            ],
        ),
    ]
