# Generated by Django 3.0.8 on 2020-07-06 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0001_initial'),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequestmaster',
            name='friendRequest_From',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='friendrequestmaster',
            name='friendRequest_To',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Loginmaster'),
        ),
    ]
