# Generated by Django 3.0.8 on 2020-07-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0001_initial'),
        ('friends', '0002_auto_20200706_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequestmaster',
            name='friendRequest_From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendRequest_From',
                                    to='login.Loginmaster'),
        ),
        migrations.AlterField(
            model_name='friendrequestmaster',
            name='friendRequest_To',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendRequest_To',
                                    to='login.Loginmaster'),
        ),
    ]
